### ISSUE TITLE
Website is outdated

### ISSUE THREAD

**Issue by igorsantos07** [essamjoubori/finance.js#24]
Some functions are missing from the said .org, such as PMT. I spent some time writing that function into the library only to notice later it's already there, but not in the "official" docs.

Please update it :(

Suggestion: make it a simple GHPage based on the README. Much better than leaving both out of sync (and making a markdown file seem like a HTML thing)

**Comment by essamjoubori** [comment]
PMT is on the github README file. Re: the .org site, I no longer own the domain; therefore, I am unfortunately unable to make any updates at this time. I am working on removing all references to the .org site.

**Comment by igorsantos07** [comment]
Omg! That's bad x_x

Push a GHPages site, based on the readme, and use it instead :)

Igor Santos
-- Desenvolvedor Web
[enviado do meu celular]
