### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by alevicki** [essamjoubori/finance.js#3]
It'd be great if you could create a bower package for this so people don't have to manually copy it over into their browser projects.

**Comment by unr** [comment]
@alevicki while this may be a helpful addition, Finance.js is already happily available on bower.js, as is any other git repo, or script.

```bash
# Git endpoint
$ bower install git://github.com/user/package.git
# URL
$ bower install http://example.com/script.js
```

Additionally, someone has already added it to bower. Try using `bower install financejs --save`.

**Comment by essamjoubori** [comment]
Please use `bower install financejs` to install the library.
